# Generated by Django 2.2.6 on 2019-10-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('img_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
